.github/workflows/remove-experimental.yml
The current GitHub Actions setup bloats npm with numerous versions because every PR generates experimental packages that aren't removed. This rework will delete any version containing `-${BRANCH_NAME}-experimental`.
=> Updated workflow to unpublish experimental packages

.github/workflows/remove-experimental.yml
Sanitize branch name for experimental package workflow: `/` will be converted to `-`.
=> Sanitize branch name for experimental package workflow

README.md, src/index.ts, tests/options.test.ts
This change ensures that the `inlineValues` option documented in the readme is correctly named `inlineParams`, which is consistent with the `params` property property by the `Statement` type.
=> Use correct naming in readme

src/utils/model.ts, src/utils/statement.ts, tests/instructions/to.test.ts, tests/meta.test.ts
In preparation for support of expressions in column values (which is landing shortly and will support [SQL functions](https://www.sqlite.org/lang_corefunc.html)), we need to stop patching the contents of JSON fields by default.
In other words:
We need to stop invoking `json_patch` by default, in order to allow for a coherent, easy-to-understand default behavior when interacting with JSON fields. When selecting nested JSON fields, we will continue to run `json_extract`, but when writing them, since we cannot predict the best transformation behavior accurately (adding properties, removing them, overwriting them, or deeply patching them), we need to default to overwriting the field value entirely.
If someone wants to run `json_patch`, `json_remove`, or similar functions, they will be able to …
=> Stop patching JSON by default

src/instructions/before-after.ts, src/instructions/ordered-by.ts, src/utils/model.ts, src/utils/statement.ts, src/validators/query.ts, tests/instructions/ordered-by.test.ts
This is a follow-up change to https://github.com/ronin-co/compiler/pull/29 and makes it possible to use field expressions in the `orderedBy` instruction.
=> Added support for expressions in `orderedBy`

src/instructions/selecting.ts, tests/instructions/including.test.ts
This is a follow-up change to https://github.com/ronin-co/compiler/pull/29 and makes it possible to use field expressions in the `including` instruction.
=> Added support for expressions in `including`

src/instructions/to.ts, src/types/model.ts, src/utils/model.ts, src/utils/statement.ts, tests/instructions/for.test.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts, tests/meta.test.ts
This change applies a shorter term for fields of type "reference": The type will now be called "link".
The term is defined as:
> a relationship between two things or situations, especially where one affects the other
...which is suitable for our current needs.
Most importantly, however, the term is more concise, while still providing the same meaning as "reference".
=> Renamed "reference" field type to "link"

src/types/model.ts, src/types/query.ts, src/utils/model.ts, tests/meta.test.ts
This change makes it possible to define a `check` attribute when adding fields to a model.
The attribute can contain an expression that determines whether the value of the field is valid, or not.
This is based on the changes added in https://github.com/ronin-co/compiler/pull/29.
=> Added `check` attribute for fields

src/types/model.ts, src/utils/model.ts, tests/meta.test.ts
This change adds a few more attributes/constraints that can be specified when adding fields to models:
- `collation`: The collation sequence for string fields.
- `increment`: Automatically increments number fields.
- `computedAs`: Allows for generating the value on read or on write using an expression.
=> Added more field constraints

src/instructions/to.ts, src/types/query.ts, src/utils/helpers.ts, src/utils/index.ts, src/utils/meta.ts, src/utils/model.ts, src/validators/query.ts, tests/errors.test.ts, tests/instructions/to.test.ts, tests/meta.test.ts, tests/types.test.ts
To prevent confusion when running queries that update the DB schema, this change evaluates aligning the query type names of the object representations of schema-modification queries further with SQLite.
In other words, the query types `create` and `drop` are now used for schema operations instead of basic operations, to avoid mixing the terminology. For example, `drop.accounts` previously sounded like you might be dropping the entire "accounts" table, to someone familiar with SQL.
- `get` => `SELECT`
- `set` => `UPDATE ... SET`
- `add` => `INSERT`
- `delete` => `DELETE`
- `count` => `SELECT COUNT(*)`
- `create.model` => `CREATE TABLE`
- `alter.model` => `ALTER TABLE`
- `drop.model` => `DROP TABLE`
=> Improved query types for object representations

src/utils/meta.ts, src/validators/query.ts, tests/meta.test.ts
This change applies another incremental improvement to the object representation of queries that can modify the database schema, which results in the TS syntax shown below.
Note that the syntax is not specifically implemented in the TS client. It is merely a result of the compiler supporting the associated object representation and the TS client now supporting functional chaining (https://github.com/ronin-co/client/pull/145).
Soon, we'll improve this syntax even further, but that requires adapting the rest of the syntax as well, not just the syntax for modifying the database schema. For example, I would like the objects to be passable as a second function argument instead of using the `to` method, but that argument is currently used to provide options (like the token) to the TS client in …
=> Improved object representation for schema changes further

src/instructions/to.ts, src/types/query.ts, src/utils/index.ts, src/utils/meta.ts, src/utils/model.ts, src/validators/query.ts, tests/instructions/to.test.ts, tests/meta.test.ts, tests/types.test.ts
Since `delete` is a [reserved keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar) in JavaScript, it can't be used a standalone variable.
=> Replaced reserved query type with different one

src/utils/statement.ts, tests/options.test.ts
Statement params should use single quotes, not double quotes! Identifiers should use double quotes.
=> Properly serialize statement params

src/index.ts, src/utils/meta.ts, src/utils/model.ts, src/utils/statement.ts, tests/meta.test.ts
This change ensures that only a single table (`ronin_schema`) is used to store the entire database schema.
=> Use a single table for database schema

src/types/model.ts, src/types/query.ts, src/utils/model.ts, tests/meta.test.ts
This change ensures that fields, indexes, triggers, and presets are stored as objects on model records, instead of being stored as arrays. The latter makes manipulating them later on more difficult.
=> When creating models, store entities as object

src/utils/model.ts, tests/meta.test.ts
This ensures that changes to fields, indexes, triggers, and presets are stored correctly in the DB.
=> Correctly patch individual model entities

README.md, src/index.ts, tests/errors.test.ts, tests/instructions/before-after.test.ts, tests/instructions/for.test.ts, tests/instructions/including.test.ts, tests/instructions/limited-to.test.ts, tests/instructions/ordered-by.test.ts, tests/instructions/selecting.test.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts, tests/meta.test.ts, tests/options.test.ts, tests/types.test.ts
This change simplifies the programmatic interface even further, by making models an option that does not need to be provided explicitly, since models may also be created inside the transaction itself, using a query.
=> Do not require models to be provided

src/types/model.ts, src/utils/helpers.ts, src/utils/model.ts, tests/fixtures/utils.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts, tests/meta.test.ts
This change makes it possible for subsequent queries within the same transaction to make use of changes made to model entities in previous queries:
```typescript
await batch(() => [
alter.model('account').create.field({ slug: 'email' }),
add.account.to({ email: 'test@site.org' })
]);
```
This was already previously possible with queries that only affected top-level attributes of models (see below), but not yet for queries that only affect nested model entities, meaning fields, indexes, triggers, or presets.
```typescript
await batch(() => [
alter.model('account').to({ slug: 'users' }),
add.user.to({ name: 'Test' })
]);
```
=> Update models for subsequent queries

src/index.ts, src/instructions/to.ts, tests/fixtures/data.json, tests/fixtures/utils.ts, tests/instructions/to.test.ts
This change adds output transformation assertions for all tests of the `to` query instruction, which means covering the cases in which records are created or updated.
=> Added output tests for creating and updating records

src/index.ts, src/instructions/before-after.ts, src/instructions/ordered-by.ts, src/instructions/to.ts, src/instructions/with.ts, src/utils/helpers.ts, src/utils/pagination.ts, tests/fixtures/data.json, tests/fixtures/utils.ts, tests/instructions/before-after.test.ts, tests/instructions/for.test.ts, tests/instructions/limited-to.test.ts, tests/instructions/ordered-by.test.ts, tests/instructions/selecting.test.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts, tests/meta.test.ts
This change brings back automatic pagination cursors for the output transformation, in cases in which the amount of records is limited using the `limitedTo` instruction, meaning cases in which pagination is activated explicitly.
=> Added pagination cursors in output

README.md, src/index.ts
At the moment, as mentioned on Slack by @colodenn, the type of a `Transaction` is incomplete, because our build tool removes the types of internal methods, which that type relies on.
By splitting out the configuration type into a dedicated interface, we are preventing the build tool from stripping it.
=> Ensure option types are publicly available

src/index.ts, src/instructions/including.ts, src/instructions/ordered-by.ts, src/instructions/selecting.ts, src/instructions/to.ts, src/utils/helpers.ts, src/utils/index.ts, src/utils/model.ts, src/utils/statement.ts, tests/options.test.ts
This option was already documented in https://github.com/ronin-co/compiler/pull/58 (check out the readme) and allows for optionally aliasing columns that are duplicated between multiple joined tables.
This is a prerequisite of using `bun:sqlite`, because that particular SQLite driver does not allow for natively expanding column names, which most other SQLite drivers that return objects do.
=> Added `expandColumns` option

README.md, src/index.ts, src/instructions/including.ts, src/instructions/selecting.ts, src/instructions/to.ts, src/types/model.ts, src/types/result.ts, src/utils/helpers.ts, src/utils/index.ts, src/utils/model.ts, src/utils/statement.ts, tests/instructions/including.test.ts, tests/instructions/limited-to.test.ts, tests/instructions/ordered-by.test.ts, tests/instructions/selecting.test.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts, tests/options.test.ts, tests/types.test.ts
This change makes it possible for the `transaction.formatResults` method to handle results from joined tables.
Additionally, it introduces a second argument for `transaction.formatResults`, which allows for handling database driver results that are not raw (rows being arrays of values) but instead pre-formatted by the driver (rows being objects), by normalizing those before processing them:
```typescript
// Passing `rawResults` (rows being of arrays of values) provided by the database (ideal)
const results: Array<Result> = transaction.formatResults(rawResults);
// Passing `objectResults` (rows being of objects) provided by a driver
const results: Array<Result> = transaction.formatResults(objectResults, false);
```
Lastly, the change also deletes the `group` field type, in favor of …
=> Added support for joins in output formatting

src/index.ts, src/instructions/including.ts, src/instructions/selecting.ts, src/types/result.ts, src/utils/helpers.ts, tests/instructions/including.test.ts, tests/options.test.ts
This change covers 4 more test cases for output formatting, which means only 24 are remaining.
Specifically, the tests assert the scenarios in which multiple records are being joined into one record.
=> Assert multiple records being joined into one

src/instructions/including.ts, src/instructions/selecting.ts, src/utils/helpers.ts, tests/instructions/including.test.ts
This change adds output assertions for all remaining tests in `tests/instructions/including.test.ts`, which is the test file used to assert queries that contain joins.
=> Added remaining output tests for joins

src/types/result.ts, tests/fixtures/data.json, tests/instructions/for.test.ts
This change adds output assertions for all remaining tests in the `tests/instructions/for.test.ts` file (as mentioned before, the name of the actual instruction is not final — in prod it is currently called `including`).
=> Assert remaining default query presets (like default joins)

src/index.ts, src/types/result.ts, tests/fixtures/data.json, tests/fixtures/utils.ts, tests/instructions/before-after.test.ts, tests/instructions/including.test.ts
This change ensures that the test suite asserts all possible outputs (and therefore also pagination cursors) related to records getting paginated, meaning cases in which a `limitedTo` instruction is provided for a query.
=> Assert pagination (limited amount of records)

src/utils/model.ts, tests/fixtures/utils.ts, tests/meta.test.ts
This change makes it possible to create a model that contains a field of type "link" whose target is the model itself.
=> Let models reference themselves

src/index.ts, src/types/result.ts
The TypeScript client package currently requires the types of all fields to be listed in the compiler result, since the client needs to format certain fields (such as fields of type "date") whose type cannot be serialized/represented in the format in which the compiler output is sent to the client (JSON).
=> Added model field types to results

src/index.ts, src/types/query.ts, tests/types.test.ts
This changes guarantees that the order which results are provided by the compiler is the same order in which queries were provided to the compiler.
=> Ensure correct order of results

src/types/query.ts
The exported `QueryType` was not yet covering all query types!
=> Improved query types further

src/utils/model.ts, tests/meta.test.ts
This change ensures that the name of fields is auto-generated from their slug.
=> Added default name for fields

src/index.ts, src/utils/helpers.ts
This change makes it possible to pass a generic argument when formatting the database results, like this:
```typescript
const results: = transaction.formatResults<Record>(rawResults);
```
=> Accept generic argument when formatting results

src/index.ts, src/utils/model.ts, tests/meta.test.ts
This change ensures that any query that alters the database schema (`create.model`, `alter.model`, or `drop.model`) correctly returns an object that matches the `Model` type.
=> Correctly format model entities

src/index.ts
This change was missing from https://github.com/ronin-co/compiler/pull/79 and ensures that the compiler doesn't crash if no model entities are defined for a given model that is being retrieved.
=> Handle missing model entities

src/utils/model.ts, tests/meta.test.ts
This pull request ensures that trigger statements such as `SELECT`, `INSERT`, and others are properly wrapped in BEGIN and END, and are separated by semicolons (`;`). For more details, please refer to the [SQLite documentation](https://www.sqlite.org/lang_createtrigger.html).
=> Wrap trigger statements in `BEGIN` & `END`

src/utils/statement.ts, tests/options.test.ts
Wrap objects in SQLite [`json()`](https://www.sqlite.org/json1.html#jmini) to prevent escaping issues and ensure correct storage.
=> Wrap object with SQLite `json`

.github/workflows/publish-experimental.yml, .github/workflows/publish-manually.yml, .github/workflows/remove-experimental.yml, .github/workflows/validate.yml, .gitignore, LICENSE, README.md, bunfig.toml
This change makes use of https://github.com/ronin-co/actions/pull/1 and reports the code coverage to [Codecov](https://about.codecov.io).
=> Report code coverage to Codecov

README.md
This change ensures the same consistent style for all readme badges:
Note that the last badge is currently intentionally automatically using a slightly yellowish green, since it gets more yellowish the larger the install size of the package is.
=> Ensure consistent readme badge style

src/utils/model.ts, tests/meta.test.ts
SQLite does not support statement parameters in schema statements, which is currently blocking a [different PR](https://github.com/ronin-co/cli/actions/runs/12572461587/job/35044473783), so we have to stop using them for indexes and triggers.
- https://github.com/sqlite/sqlite/blob/f7fcf7f910dcbc765eac670d74f36ccddbfe81c3/src/attach.c#L453
- https://github.com/sqlite/sqlite/blob/f7fcf7f910dcbc765eac670d74f36ccddbfe81c3/src/attach.c#L515
- https://github.com/sqlite/sqlite/blob/f7fcf7f910dcbc765eac670d74f36ccddbfe81c3/test/triggerE.test#L50
Since schema-altering statements like trigger creation, index creation and so on are anyways not run by end-users, the SQLite team likely intentionally didn't want to prevent SQL injections here. Those kinds of queries are also not run repeatedly, so the …
=> Avoid using params for schema statements

src/utils/statement.ts, tests/options.test.ts
This change ensures that query symbols are properly escaped when being stored in the root model table.
=> Properly serialize expressions

src/types/model.ts, src/utils/model.ts
This change ensures that the `ModelField` type changes which attributes are available based on the field type.
=> Separate field attributes based on type

src/types/model.ts, tests/meta.test.ts
This change was missing from https://github.com/ronin-co/compiler/pull/93 and ensures that `Extract` works:
```typescript
type LinkField = Extract<ModelField, { type: 'link' };
```
=> Ensure correct field type

src/types/model.ts
The `blob` field type was missing from the TypeScript declarations!
=> Added missing `blob` field type

src/types/model.ts
This change was missing from https://github.com/ronin-co/compiler/pull/94.
```typescript
// worked
type LinkField = Extract<ModelField, { type: 'link' };
// didn't work
type DateField = Extract<ModelField, { type: 'date' };
```
Now both of them are working. Meaning all field types are working.
=> Allow for extracting field types

src/utils/statement.ts, tests/instructions/to.test.ts
This change ensures that, if a field is set to `null`, a correct SQL statement is generated.
=> Correctly handle empty fields

src/model/index.ts, tests/meta.test.ts
Until now, creating indexes and triggers required dedicated queries.
With this change, indexes and triggers can be passed as part of a `create.model(...)` query, which causes the compiler to compose the respective SQLite statements automatically.
=> Allow for passing indexes and triggers when creating models

src/index.ts
This change ensures that private properties of transactions are not only hidden in the types, but also in the exposed class instances themselves, since we no longer need them to be publicly accessible — not even for ourselves.
=> Hide private properties

src/index.ts, src/instructions/including.ts, src/instructions/selecting.ts, src/types/model.ts, src/utils/helpers.ts, src/utils/index.ts, tests/fixtures/utils.ts, tests/instructions/including.test.ts
Previously, it was only possible to include multiple nested records when retrieving a single root record.
With the current change, it is now possible to include multiple nested records per root record, even when retrieving multiple root records.
=> Support retrieving multiple records with multiple nested records

src/model/defaults.ts, src/types/model.ts, tests/instructions/for.test.ts
This change ensures that defining `kind: 'many'` for a field with `type: 'link'` works as expected.
=> Made one-to-many relationships work

src/index.ts, src/instructions/including.ts, src/instructions/ordered-by.ts, src/instructions/selecting.ts, src/instructions/to.ts, src/model/index.ts, src/utils/helpers.ts, src/utils/statement.ts, tests/instructions/including.test.ts
This change ensures that the compiler exports a function called `getQuerySymbol`, which allows for determining whether a given value is a query symbol (like an expression or a sub query), or not.
=> Export function for detecting query symbols

src/instructions/to.ts, tests/instructions/to.test.ts
As mentioned in the code comment within the PR diff, we previously had to implicitly add the `id` field to the `selecting` instruction in certain cases, but since IDs are now generated in the DB (as of https://github.com/ronin-co/compiler/pull/97), that is no longer necessary.
=> Stop implicitly selecting ID

src/instructions/selecting.ts, src/utils/statement.ts, tests/instructions/selecting.test.ts
So far, the `selecting` instruction only allowed for selecting specific fields, like so:
```typescript
get.accounts.selecting(['handle']);
```
With the current change, the instruction is gaining support for [glob](https://en.wikipedia.org/wiki/Glob_(programming))-like patterns, which allows for matching multiple different fields at once, and most importantly also excluding certain fields:
```typescript
// Matches all fields at the root level
get.accounts.selecting(['*']);
// Matches all fields on any level
get.accounts.selecting(['**']);
// Excludes certain fields
get.accounts.selecting(['!handle']);
```
The aforementioned pattern components can then be combined as well. For example, like this:
```typescript
// Matches all fields nested under `ronin`
get.accounts.selecting(['ronin.*']); …
```
=> Added patterns for `selecting`

src/instructions/to.ts, src/model/defaults.ts, tests/instructions/for.test.ts
This ensures that one-to-many relationships do not return unnecessary columns when they are resolved.
=> Ensure perfect results for one-to-many relationships

src/index.ts, tests/instructions/for.test.ts, tests/instructions/including.test.ts
This change ensures that cases in which related records are missing still result in a correct output.
=> Handle cases in which related records are missing

src/index.ts, src/types/query.ts
This change exports the TypeScript types for the query types `create`, `alter`, and `drop`.
=> Export more query types

src/index.ts, src/model/index.ts, src/types/query.ts, src/utils/statement.ts, tests/fixtures/data.json, tests/instructions/to.test.ts, tests/instructions/with.test.ts
This change ensures that trying to insert values into fields of type `blob` no longer causes a crash.
=> Added support for blob field type

src/index.ts, src/instructions/to.ts, src/model/index.ts, src/types/query.ts, src/utils/index.ts, tests/instructions/to.test.ts
Previously, it has already been possible to update existing records and:
- Add another record to a "many"-cardinality link field
- Remove a record from a "many"-cardinality link field
- Overwrite the current list of records in a "many"-cardinality link field with new ones
However, creating entirely new records and, at the same time, defining the list of records in a "many"-cardinality link field on that record has not yet been supported so far.
As of the current change, this is now possible:
```typescript
add.account.to({
handle: 'elaine',
followers: [{ handle: 'david' }]
});
```
Note that neither the `followers.containing` (adding records) nor the `followers.notContaining` (removing records) instructions are supported for `add` queries, since neither of them would make sense in that …
=> Allow for providing "many" relations while creating records

src/index.ts, src/types/result.ts, src/utils/pagination.ts, tests/types.test.ts
This change exports a `ResultRecord` type from the compiler, which defines a record stored in a RONIN database.
=> Export record type

src/index.ts, src/utils/index.ts, tests/types.test.ts
Previously, if the option `expandColumns: true` was passed to the compiler, [this error](https://discord.com/channels/1099977902629589095/1331647781558947942/1331786460009070602) reported by a customer on Discord was happening.
With the current change, the error no longer happens and the results for `count` queries are always returned reliably.
=> Always return correct `count` query results

README.md, src/index.ts, src/instructions/selecting.ts, src/utils/index.ts, tests/instructions/before-after.test.ts, tests/instructions/for.test.ts, tests/instructions/including.test.ts, tests/instructions/limited-to.test.ts, tests/instructions/ordered-by.test.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts, tests/meta.test.ts, tests/options.test.ts, tests/types.test.ts
With this change, all columns will now be selected by default, without requiring the `expandColumns` option.
As a result, the SQL statements of all tests are now much more detailed, but we will also be able to remove the Wasm driver from the engine.
=> Explicitly select all columns by default

README.md, src/index.ts, src/instructions/including.ts, src/instructions/selecting.ts, src/utils/helpers.ts, tests/fixtures/utils.ts, tests/instructions/including.test.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts
This change resolves a bug that was causing joined records that were being "hoisted upwards" (as shown in [this test](https://github.com/ronin-co/compiler/blob/40e16e490ac99b9230a2da03197eae91f4560e9d/tests/instructions/including.test.ts#L700)) to not be formatted correctly.
In addition, the performance of the test suite is being improved dramatically by removing the Wasm SQLite driver.
=> Ensure hoisting joined records works correctly

src/model/index.ts, src/utils/index.ts, tests/instructions/to.test.ts, tests/meta.test.ts, tests/options.test.ts, tests/types.test.ts
So far, we have only been selecting columns in the SQL statements generated by `get` queries.
With the current change, the queries of type `add`, `set`, and `remove` will do the same, which ensures that their results are always formatted correctly.
=> Select columns when modifying records

src/model/defaults.ts, tests/meta.test.ts
This change ensures that the `idPrefix` attribute that is added to every model is always lowercase by default.
=> Ensure lowercase ID prefixes by default

src/instructions/with.ts, tests/instructions/before-after.test.ts, tests/instructions/for.test.ts, tests/instructions/including.test.ts, tests/instructions/to.test.ts, tests/instructions/with.test.ts, tests/meta.test.ts, tests/types.test.ts
This change ensures that providing a query with an empty "OR" condition does not cause an SQL syntax error.
For example, the query might look like this:
```typescript
get.accounts.with({
handle: []
});
```
Instead of causing an SQL syntax error, the query above will now return all records, since no matchers are provided.
We're purposefully doing this instead of erroring, because it allows for composing RONIN queries programmatically more easily, which is an important aspect of our query language:
```typescript
const getAccounts = (limiter?: Array<string>) => {
return get.accounts.with.handle(limiter);
};
```
=> Gracefully handle empty OR conditions

src/utils/index.ts, tests/instructions/before-after.test.ts
This change ensures that the compiler doesn't throw an error if the `before` or `after` instructions contain `undefined` as their value, as such a value must be supported for the purpose of composition:
```typescript
const loadComments = (after?: string) => {
return get.comments({
with: {
post: postId,
},
limitedTo: 5,
after,
});
};
```
This also makes it possible to revert https://github.com/AndyBitz/site/pull/37.
=> Gracefully handle undefined pagination cursor

src/model/defaults.ts, tests/options.test.ts
This change ensures that the compiler can receive models that already include default fields and presets.
Instead of attaching the default fields and presets again to those models, it now checks if they already exist and doesn't set them if they are already present.
=> Avoid repeating default fields and presets

src/instructions/to.ts, src/model/index.ts, src/types/query.ts, src/utils/index.ts, tests/errors.test.ts, tests/fixtures/utils.ts, tests/instructions/to.test.ts, tests/meta.test.ts, tests/options.test.ts
This change updates the syntax of `add` queries from this...
```typescript
add.account.to({
name: 'Elaine',
handle: 'elaine'
});
```
...to this:
```typescript
add.account.with({
name: 'Elaine',
handle: 'elaine'
});
```
Like this, the syntax is more cohesive.
=> Support `with` instruction for `add` queries

src/types/query.ts
When altering models, it is not possible to pass any model entity (fields, indexes, triggers, or presets), as those must be altered individually. The change ensures that the types reflect this.
Furthermore, the `idPrefix` attribute can also only be provided when the model is created.
=> Do not allow model entities upon altering

src/instructions/using.ts, src/utils/index.ts
This applies an internal change that does not affect the behavior of the compiler.
The `for.ts` file in the `instructions` folder is now correctly named `using.ts`, just like its respective `using.test.ts` file.
=> Ensure correct file name for instructions

src/instructions/including.ts, src/instructions/selecting.ts, tests/instructions/including.test.ts
The compiler currently already supports joining other records into the records that are being retrieved in the main query:
```typescript
get.accounts.including(f => ({
members: get.members.with.account(f.id)
}));
```
With the current change, it now also becomes possible to join the count of records instead of the records themselves:
```typescript
get.accounts.including(f => ({
memberAmount: count.members.with.account(f.id)
}));
```
=> Allow for including count of joined records

src/model/index.ts, src/types/model.ts, tests/meta.test.ts
On RONIN, link field constraints are designed to prevent the existence of children that don't have parents, and link field actions exist to automatically handle the children if something happens to the parents.
It therefore doesn't make sense to offer link field actions for many-cardinality relationships, since, in those cases, parents are referencing children, and parents should never be affected if something happens to the children, since there can be many children and only one parent.
Lastly, if the parents disappear, their references to the children should also disappear.
=> Prevent actions for many-cardinality link fields

src/instructions/using.ts, tests/instructions/using.test.ts
This change makes it possible to resolve the related records of all link fields at once, without specifying each of the link fields in the `using` query instruction:
```typescript
get.member.using(['links']);
```
The syntax will be evolved further in the future.
=> Allow for resolving all link fields at once

src/index.ts, src/model/index.ts, src/types/query.ts, src/types/result.ts, tests/types.test.ts
In SQLite, it's not possible to dynamically generate a list of SQL statements for a list of tables. Instead, the tables that are being addressed must be known ahead of time.
To make this possible on RONIN, we introduced the keyword `all` as a model slug a long time ago, which makes the query run for all models, instead of just one model.
I'm now bringing this keyword back, because I consider it to be the most effective way to run a query for all models, at the moment of writing. As an example, this is how the rows in all tables can be counted at once:
```typescript
count.all()
```
Similarly, this is how you load the most recently created 2 records of all tables:
```typescript
get.all({
orderedBy: { descending: ['ronin.createdAt'] },
limitedTo: 2
});
```
We will evolve this syntax further …
=> Make it possible to run queries for all models

src/instructions/before-after.ts, src/utils/index.ts, tests/instructions/before-after.test.ts
This change ensures that the following query works without problems:
```typescript
count.accounts.before('1667575193779');
```
In other words: The compiler normally requires a `limitedTo` instruction to be present when paginating. When counting, however, people often want to determine the total amount of available records before or after a given counter, so we should not require the `limitedTo` instruction in that case.
=> Ensure correct pagination while counting

src/utils/statement.ts, tests/meta.test.ts, tests/options.test.ts
This change ensures that statement parameters are correctly inlined when the `inlineParams` config option is used.
Previously, booleans and integers were incorrectly inlined as strings, for example.
=> Correctly inline field values

src/instructions/with.ts, src/utils/statement.ts, tests/instructions/with.test.ts
Previously, when retrieving records, empty fields were asserted using `= NULL`, which is not valid in SQLite.
Instead, we are now correctly using `IS NULL`.
=> Correctly assert empty fields

README.md, src/index.ts, src/instructions/including.ts, src/instructions/selecting.ts, src/instructions/to.ts, src/model/index.ts, src/utils/helpers.ts, src/utils/index.ts, tests/options.test.ts
This change ensures that default values can be generated as part of the SQL statement, instead of requiring the database to generate them.
=> Temporarily inline default value expressions

src/model/defaults.ts, tests/meta.test.ts
This change ensures that updating the `slug` of a model does not cause its name, plural name, or other attributes to be re-generated automatically.
Only the plural slug and table name of a model will be re-generated in that case.
=> Do not re-generate model attributes if slug changes

src/types/model.ts, tests/meta.test.ts
As part of the ongoing effort to improve our types across all packages, this is a small improvement to model index types that makes it such that an index MUST include at least one field.
=> Add index fields type guards

src/model/index.ts, src/types/model.ts, tests/meta.test.ts
The current implementation of the syntax package wraps queries within `trigger.effects` using a query symbol. This causes issues with the compiler, as it incorrectly interprets the query symbol as a query type, such as add or create, due to object destructuring. This PR addresses this issue to ensure proper handling of queries by the compiler.
=> Allow for passing trigger effects as query symbols

src/model/index.ts, tests/meta.test.ts
This change ensures that, when the slug of a field is changed, all of its other attributes are not lost.
=> Correctly update fields when changing their slug

src/model/index.ts
I am currently addressing a bug that prevents models from being cloned. To resolve this issue, we are utilizing `JSON.parse(JSON.stringify())` to ensure that the models can be properly cloned.
=> Ensure that models are altered reliably

src/instructions/to.ts, src/model/defaults.ts, src/model/index.ts, src/utils/helpers.ts, tests/options.test.ts
This change ensures that, if the `inlineDefaults` option is passed, the metadata of records is generated correctly.
=> Ensure correct record metadata

src/index.ts, src/model/index.ts, src/types/query.ts, tests/types.test.ts
At the moment, it is already possible to address all models at once with a single query:
```typescript
get.all();
count.all();
// etc.
```
Those queries are helpful because they avoid needing to first resolve the list of models before being able to compose queries for the resolved models. SQLite does not provide a solution for dynamically composing queries like that either, so we integrated it into the compiler instead.
The current change applies one more improvement to those queries, by allowing for only selecting the linked models of a specific model, which would otherwise not be possible:
```typescript
get.all.for('member');
```
Assuming that the "member" model, for example, has two link fields pointing to the models "account" and "team", then the `get.all` query above would only …
=> Allow for resolving related models

src/index.ts, src/types/query.ts, src/utils/index.ts, tests/options.test.ts, tests/types.test.ts
This change ensures that queries addressing all models (e.g. `get.all()`) still return correct results instead of not showing up in the results at all, in the case that no models are available.
=> Handle case in which no models exist

src/index.ts, src/types/query.ts, src/utils/index.ts, tests/types.test.ts
At the moment, mixing a query that affects multiple models (such as `get.all()`) between other queries causes the compiler to crash, which shouldn't happen:
```typescript
get.accounts();
get.all();
get.teams();
```
With the current change, the bug is prevented and the queries are compiled as expected.
=> Allow for mixing multi-model queries in any order

src/index.ts, src/types/query.ts, tests/types.test.ts
This change allows for providing instructions that apply only to a specific model, when using queries that affect all models.
In other words, considering that the following query retrieves the records of all models:
```typescript
get.all();
```
The following query would then do the same, but limit the records of the "account" model to 10:
```typescript
get.all({
on: {
accounts: { limitedTo: 10 }
}
});
```
This change is not necessary, since the same can be accomplished by simply using an additional, separate query.
In order to ensure perfect performance (no unnecessary queries) however, and because the additional syntax complexity is limited strictly to `all` queries, using an additional `on` query instruction is more advantageous.
=> Allow for providing model-specific instructions

src/index.ts, src/types/query.ts, tests/types.test.ts
This change ensures that providing model-specific instructions for a query that affects all models (such as `get.all()`) works correctly, by ensuring that fields are selected as desired.
=> Ensure correct model-specific queries

src/index.ts, src/instructions/selecting.ts, src/instructions/to.ts, src/instructions/using.ts, src/model/defaults.ts, src/model/index.ts, src/types/model.ts, src/types/query.ts, src/utils/constants.ts, src/utils/helpers.ts, src/utils/index.ts, src/utils/statement.ts, tests/errors.test.ts, tests/instructions/before-after.test.ts, tests/instructions/including.test.ts, tests/instructions/ordered-by.test.ts, tests/instructions/to.test.ts, tests/instructions/using.test.ts, tests/meta.test.ts, tests/options.test.ts
This change exports the list of all query types from the compiler, to ensure that other parts of the system (such as the client) don't need to re-define them.
=> Export list of query types

src/instructions/selecting.ts, tests/instructions/including.test.ts
This change ensures that the `including` instruction works correctly if an ephemeral field is provided whose slug is also, at the same time, used for a stored field.
Check out the newly added test cases for examples of scenarios in which this would occur.
=> Allow for overwriting stored fields

src/types/result.ts
This change splits out the `ResultRecord` type into a "base type" and the actual type to be used as a result.
Additionally all properties have been updated to add some basic documentation comments.
=> Improve `ResultRecord` type readability

src/index.ts
This change fixes a small oversight as part of #162 where the new `ResultRecordBase` type was not actually exported from the package.
=> Added `ResultRecordBase` type to root export

src/model/index.ts, tests/meta.test.ts
This change ensures that the `slug` attribute of model entities (fields, indexes, etc.) is never stored as part of the attributes of the model entity within the model.
In other words, it prevents a scenario like this one from occurring:
```
fields: {
test: { slug: test, ... }
}
```
=> Correctly store model entity slug

src/model/index.ts, tests/instructions/with.test.ts, tests/meta.test.ts
This change ensures that providing an object as a default value for a JSON field (instead of a string) works just fine!
=> Accept objects as JSON default values

src/index.ts
This change was missing from https://github.com/ronin-co/compiler/pull/168 and ensures that the TypeScript types for the `list` query type are being exported.
=> Expose `list` query type

src/instructions/selecting.ts, src/instructions/using.ts, tests/instructions/selecting.test.ts
When executing a `get` query that includes both `selecting` and `using` clauses with identical fields, the generated SQL statement incorrectly attempts to query these fields twice. 
This results in a SQL statement such as `SELECT id, name, id, name ...`.
=> Don't duplicate fields from `selecting` and `using`

src/utils/statement.ts, tests/instructions/to.test.ts
This change ensures that empty values are accepted for JSON and Blob fields.
=> Allow empty value for JSON and Blob fields

src/model/index.ts, tests/meta.test.ts
This change ensures that it will no longer be possible to provide invalid JSON as the default value of a JSON field.
=> Reject invalid JSON as field default value

bun.lock, package.json, tests/fixtures/utils.ts
This change was missing from https://github.com/ronin-co/compiler/pull/177 and ensures the correct versions of peer dependencies.
=> Use correct peer dependency versions

src/index.ts, src/utils/constants.ts
This change ensures the following exports:
```typescript
QUERY_TYPES
QUERY_TYPES_READ
QUERY_TYPES_WRITE
DML_QUERY_TYPES
DML_QUERY_TYPES_READ
DML_QUERY_TYPES_WRITE
DDL_QUERY_TYPES
DDL_QUERY_TYPES_READ
DDL_QUERY_TYPES_WRITE
```
Before the change, only the following exports were present:
```typescript
QUERY_TYPES
DML_QUERY_TYPES
DML_QUERY_TYPES_READ
DML_QUERY_TYPES_WRITE
DDL_QUERY_TYPES
```
=> Split query types into read and write

src/index.ts, src/instructions/before-after.ts, src/instructions/using.ts, src/model/index.ts, src/utils/helpers.ts, src/utils/index.ts, src/utils/statement.ts, tests/errors.test.ts, tests/instructions/before-after.test.ts, tests/instructions/to.test.ts, tests/instructions/using.test.ts, tests/meta.test.ts
The name "RoninError" is pretty meaningless, since it might stem from any component of the RONIN platform.
With the name "CompilerError", it becomes clear that the error stems from the compiler.
=> Provide helpful name for compiler errors
